In [8]:
import numpy as np

Number_of_States = 36
Number_of_Actions = 4
obstacles = [7,10,25] #Specifies where the obstacles are
actions = [0,1,2,3] # 0-Up 1-Down 2-Left 3-Right
state_rewards = []
final_state = []

#State rewards are set to -1
for state in range(0,Number_of_States+1):
    state_rewards.append(-1)

#State rewards for obstacle states are set to -5
for obstacle in obstacles:
    state_rewards[obstacle] = -5

    
for state in range(0,Number_of_States):
    final_state.append(False)

#The index position of 21 is set as final state    
final_state[21] = True

#Q-Table is initialized as zeros
Q_values = np.zeros([Number_of_States,Number_of_Actions], dtype=float)

print(Q_values)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
def select_epsilon_greedy_action(epsilon, state):
    result = np.random.uniform()
    if result < epsilon:
        return np.random.randint(0, 4) # Random action (Up,Down,left,right)
    else:
        return np.argmax(Q_values[state]) # Greedy action for state


In [10]:
def apply_action(state,action):
    
    next_state = 0
    if(action ==0):
        #Only top-most row have problem
        if(state>5):
            next_state = state-6
            #return state_rewards[next_state], next_state
    elif(action == 1):
        #Only Bottom-most row have problem
        if(state<29):
            next_state = state+6
            #return state_rewards[next_state], next_state
    elif(action ==2):
        #Only Left-most row have problem
        if(state%6 != 0):
            next_state = state-1
            #return state_rewards[next_state], next_state
        
    else:
        #Only Right-most row have problem
        if(state%6 != 5):
            next_state = state+1
            #return state_rewards[next_state], next_state
    return state_rewards[next_state],next_state  



In [32]:
print(apply_action(36,2))

(-1, 30)


In [13]:
num_episodes = 1000
epsilon = 0.2
discount = 0.9 # Discount Factor is set here

for episode in range(num_episodes+1):
    initial_state = 0 # STarting state is specified here
    state = initial_state
    #print("Episode Begins",episode)
    while not final_state[state]: # Run until the end of the episode
        
        
        #next_state = 37
        # Select action
    
        action = select_epsilon_greedy_action(epsilon, state)
        reward, next_state = apply_action(state, action)
           
            
        # Improve Q-values with Bellman Equation
        if final_state[next_state]:
            Q_values[state][action] = reward
        else:
            Q_values[state][action] = reward + discount * max(Q_values[next_state])
        state = next_state
        #print("Episode Ends",episode)

# Print Q-values to see if action right is always better than action left
# except for states 0 and 6, which are terminal states and you cannot take
# any action from them, so it does not matter.
print('Q-values are:')
print(Q_values)
action_dict = {0:'Up', 1:'Down',2:'Left',3:'Right'}
state = 0
for Q_vals in Q_values:
    print('Best action for state {} is {}'.format(state, 
                                             action_dict[np.argmax(Q_vals)]))
    state += 1
state = 0
cumi_cost = 0
print("Best Path is:")
while not final_state[state]:
    action = np.argmax(Q_values[state])
    reward,next_state = apply_action(state,action)
    cumi_cost += reward
    state = next_state
    print(state)
print("Cumilative Cost",cumi_cost)

Q-values are:
[[ -6.86189404  -6.5132156   -6.86189404  -6.5132156 ]
 [ -6.86189404 -10.12579511  -6.86189404  -6.12579511]
 [ -6.86189404  -5.6953279   -6.5132156   -5.6953279 ]
 [ -6.86189404  -5.217031    -5.217031    -5.217031  ]
 [ -6.86189404  -5.          -5.6953279   -4.68559   ]
 [ -5.6953279   -4.0951      -4.0951      -6.86189404]
 [ -6.86189404  -6.12579511  -6.86189404 -10.12579511]
 [ -6.5132156   -5.6953279   -6.5132156   -5.6953279 ]
 [ -6.12579511  -5.217031   -10.12579511  -5.217031  ]
 [ -5.6953279   -4.68559     -5.6953279   -6.71      ]
 [ -5.217031    -1.9         -2.71        -4.0951    ]
 [ -4.0951      -3.439       -5.          -5.6953279 ]
 [ -6.5132156   -5.6953279   -6.86189404  -5.6953279 ]
 [-10.12579511  -5.217031    -6.12579511  -5.217031  ]
 [ -5.6953279   -4.68559     -5.6953279   -4.68559   ]
 [ -5.217031    -4.0951      -5.217031    -4.0951    ]
 [ -6.71        -3.439       -4.68559     -3.439     ]
 [ -3.439       -3.439       -4.0951      -4.68559 